[package]
name = "cx-data-typechecker"
version = "0.1.0"
edition = "2024"

[dependencies]
speedy = "0.8.7"

cx-data-ast = { path = "../cx-data-ast" }
cx-util = { path = "../cx-util" }
uuid = { version = "1.17.0", features = ["v4"] }