# Generates the low-poly bush and leaf SVG symbols used behind the site.
import math, random
from pathlib import Path

def f(x): return str(round(x))

def pts(ps): return " ".join(f"{f(x)},{f(y)}" for x, y in ps)

def poly(rng, cx, cy, r, n, rot=None):
    rot = rng.uniform(0, 2 * math.pi) if rot is None else rot
    step = 2 * math.pi / n
    out = []
    for i in range(n):
        a = rot + i * step + rng.uniform(-0.22, 0.22) * step
        rr = r * rng.uniform(0.86, 1.08)
        out.append((cx + rr * math.cos(a), cy + rr * math.sin(a)))
    return out

def leaf(x, y, ang, L, cls):
    W = L * rng_leaf.uniform(0.34, 0.46)
    k = rng_leaf.uniform(0.35, 0.55)
    local = [(0, 0), (L * k, -W), (L, 0), (L * (k + 0.08), W)]
    c, s = math.cos(ang), math.sin(ang)
    ps = [(x + px * c - py * s, y + px * s + py * c) for px, py in local]
    return f'<polygon class="{cls}" points="{pts(ps)}"/>'

def facets(rng, cx, cy, ps):
    out = []
    ox, oy = cx + rng.uniform(-4, 4), cy + rng.uniform(-4, 4)
    n = len(ps)
    i = rng.randrange(n)
    out.append(f'<polygon class="fh" points="{pts([(ox, oy), ps[i], ps[(i + 1) % n]])}"/>')
    j = (i + n // 2) % n
    out.append(f'<polygon class="fl" points="{pts([(ox, oy), ps[j], ps[(j + 1) % n]])}"/>')
    return out

def layer(rng, R, lobe, count, cls, leaves, jitter):
    out = [f'<polygon class="{cls}" points="{pts(poly(rng, 0, 0, R * 0.92, 12, 0))}"/>']
    tips = []
    for i in range(count):
        t = (i + 0.5) / count
        a = t * math.pi / 2 + rng.uniform(-jitter, jitter)
        r = lobe * rng.uniform(0.7, 1.2)
        rr = R + rng.uniform(-0.15, 0.1) * lobe
        cx, cy = rr * math.cos(a), rr * math.sin(a)
        ps = poly(rng, cx, cy, r, rng.randint(5, 6))
        out.append(f'<polygon class="{cls}" points="{pts(ps)}"/>')
        if i % 2 == 0:
            out += facets(rng, cx, cy, ps)[(i // 2) % 2:][:1]
        tips.append((cx, cy, r, a))
    for cx, cy, r, a in list(tips):
        for _ in range(1):
            b = a + rng.uniform(-0.9, 0.9)
            d = r * rng.uniform(0.72, 0.9)
            out.append(f'<polygon class="{cls}" points="{pts(poly(rng, cx + d*math.cos(b), cy + d*math.sin(b), r * rng.uniform(0.32, 0.45), 4))}"/>')
    for _ in range(leaves):
        cx, cy, r, a = rng.choice(tips)
        b = a + rng.uniform(-0.8, 0.8)
        x, y = cx + (r - 9) * math.cos(b), cy + (r - 9) * math.sin(b)
        out.append(leaf(x, y, b + rng.uniform(-0.35, 0.35), rng.uniform(22, 32), cls))
    return out, tips

def bush(seed, scale):
    global rng_leaf
    rng = random.Random(seed)
    rng_leaf = random.Random(seed + 1)
    parts = []
    l1, _ = layer(rng, 205 * scale, 70 * scale, 6, "b1", 6, 0.05)
    l2, t2 = layer(rng, 130 * scale, 54 * scale, 5, "b2", 4, 0.06)
    l3, _ = layer(rng, 62 * scale, 40 * scale, 3, "b3", 2, 0.08)
    parts += l1 + l2 + l3
    for a in (0.55, 1.05):
        bx, by = 88 * scale * math.cos(a), 88 * scale * math.sin(a)
        for dx, dy in ((0, 0), (9, 4), (3, 10)):
            parts.append(f'<polygon class="berry" points="{pts(poly(rng, bx+dx, by+dy, 4.8, 5))}"/>')
    return "".join(parts)

rng_leaf = None
symbols = [
    f'<symbol id="{sid}" viewBox="0 0 320 320" overflow="visible">{bush(seed, scale)}</symbol>'
    for seed, scale, sid in ((7, 1.0, "bush-a"), (21, 0.82, "bush-b"))
]
symbols.append('<symbol id="drift-leaf" viewBox="-2 -9 26 18"><polygon class="dl" points="0,0 9,-7 24,0 11,7"/><polygon class="fh" points="0,0 9,-7 24,0"/></symbol>')

out = Path(__file__).resolve().parent.parent / "src/components/Foliage/symbols.ts"
out.write_text(
    "// Generated by scripts/generate-foliage.py\n"
    f"export const foliageSymbols = `{''.join(symbols)}`;\n"
)
