[package]
name = "cx-pipeline-data"
version = "0.0.0"
edition = "2024"

[features]
default = []
test = []

[dependencies]
speedy = { version = "0.8.7" }
toml = { version = "0.8" }
serde = { version = "1", features = ["derive"] }

cx-tokens = { path = "../cx-tokens" }
cx-log = { path = "../cx-log" }

cx-preparse-data = { path = "../cx-preparse-data" }
cx-ast  = { path = "../cx-ast" }
cx-thir = { path = "../cx-thir" }
cx-lmir = { path = "../cx-lmir" }
cx-target = { path = "../cx-target" }
cx-util = { path = "../cx-util" }
