[package]
name = "cx-compiler-typechecker-new"
version = "0.1.0"
edition = "2024"

[dependencies]
cx-data-typechecker = { path = "../cx-data-typechecker" }
cx-data-ast = { path = "../cx-data-ast" }
cx-util = { path = "../cx-util" }