[package]
name = "cx-ast-data"
version = "0.0.0"
edition = "2021"
autotests = false

[dependencies]
cx-util = { path = "../cx-util" }
cx-lexer-data = { path = "../cx-lexer-data" }

uuid = { version = "1.16.0", features = ["v4"] }
speedy = { version = "0.8.7" }