[package]
name = "cx-typechecker"
version = "0.0.0"
edition = "2024"

[dependencies]
cx-tokens = { path = "../cx-tokens" }
cx-thir = { path = "../cx-thir" }
cx-target = { path = "../cx-target" }
cx-hir = { path = "../cx-hir" }
cx-pipeline-data = { path = "../cx-pipeline-data" }

cx-namespace = { path = "../cx-namespace" }
cx-util = { path = "../cx-util" }
cx-log = { path = "../cx-log" }

speedy = { version = "0.8.7" }