[package]
name = "cx-mir-lowering"
version = "0.0.0"
edition = "2021"
autotests = false

[dependencies]
cx-parsing = { path = "../cx-parsing" }

cx-ast = { path = "../cx-ast" }
cx-lexer = { path = "../cx-lexer" }
cx-log = { path = "../cx-log" }
cx-mir = { path = "../cx-mir" }
cx-lmir = { path = "../cx-lmir" }
cx-tokens = { path = "../cx-tokens" }

cx-util = { path = "../cx-util" }
