[package]
name = "cx-mir-lowering"
version = "0.0.0"
edition = "2021"
autotests = false

[dependencies]
cx-hir = { path = "../cx-hir" }
cx-mir = { path = "../cx-mir" }
cx-mir-comptime = { path = "../cx-mir-comptime" }
cx-lmir = { path = "../cx-lmir" }
cx-target = { path = "../cx-target" }

cx-util = { path = "../cx-util" }
cx-log = { path = "../cx-log" }
