use super::define_errors;

define_errors! {
    COMPTIME_INVALID_OPERATION: String = "M0001" => |operation| format!("{operation} is not supported in comptime contexts");
    
    COMPTIME_POINTER_ARITHMETIC_OVERFLOW: () = "M0002" => |_| "pointer arithmetic overflowed during compile-time evaluation".into();

    COMPTIME_TYPE_LAYOUTS_UNAVAILABLE: () = "M0003" => |_| "type layouts are unavailable during comptime evaluation".into();
    COMPTIME_INVALID_POINTEE_LAYOUT: () = "M0004" => |_| "invalid pointee layout in pointer arithmetic".into();
    COMPTIME_ORDERED_POINTER_COMPARISON: () = "M0005" => |_| "ordered pointer comparisons are not supported in a comptime context".into();
    COMPTIME_DIVISION_BY_ZERO: () = "M0006" => |_| "division by zero during compile-time evaluation".into();
    COMPTIME_REMAINDER_BY_ZERO: () = "M0007" => |_| "remainder by zero during compile-time evaluation".into();
    COMPTIME_INCREMENT_UNEXPECTED: () = "M0008" => |_| "increment is handled by the execution loop".into();
    COMPTIME_POINTER_TO_INTEGER: () = "M0009" => |_| "pointer-to-integer coercions are not supported in a comptime context".into();
    COMPTIME_NON_NULL_POINTER: () = "M0010" => |_| "non-null pointer coercions are not supported in a comptime context".into();
    COMPTIME_NON_FUNCTION_TO_POINTER: () = "M0011" => |_| "cannot coerce a non-function constant to a pointer in a comptime context".into();
    COMPTIME_POINTER_COMPARISON: String = "M0012" => |value| format!("comparison of non-pointer constants {value}");
    COMPTIME_INCREMENT_NON_INTEGER: String = "M0013" => |value| format!("increment applied to non-integer constant {value}");
    COMPTIME_STEP_LIMIT: u64 = "M0014" => |steps| format!("comptime evaluation exceeded {steps} steps");
    COMPTIME_BLOCK_FELL_THROUGH: () = "M0015" => |_| "block fell through without a terminating instruction".into();
    COMPTIME_DEREFERENCE: () = "M0016" => |_| "dereference is not supported in a comptime context".into();
    COMPTIME_NON_FUNCTION_CALL: String = "M0017" => |value| format!("cannot call non-function comptime value {value}");
    COMPTIME_VARIADIC: () = "M0018" => |_| "variadic operations are not comptime-capable".into();
    COMPTIME_ASSERTION: Option<String> = "M0019" => |message| message.unwrap_or_else(|| "assertion failed at compile time".into());
    COMPTIME_INTEGER_SWITCH: () = "M0020" => |_| "integer switch fell through all cases".into();
    COMPTIME_VARIANT_SWITCH: () = "M0021" => |_| "variant switch fell through all cases".into();
    COMPTIME_UNREACHABLE: () = "M0022" => |_| "unreachable code executed at compile time".into();
    COMPTIME_APPLY_NON_STAGED: () = "M0023" => |_| "attempted to apply a non-staged value".into();
    COMPTIME_STAGED_TEMPLATE_CALL: () = "M0024" => |_| "staged template executed as a function".into();
    COMPTIME_STAGED_EXIT_CALL: () = "M0025" => |_| "staged exit executed as a function".into();
    COMPTIME_STAGED_YIELD_CALL: () = "M0026" => |_| "staged yield executed as a function".into();
    COMPTIME_STAGED_MOVE_CALL: () = "M0027" => |_| "staged move executed as a function".into();
    COMPTIME_STAGED_USE_CALL: () = "M0028" => |_| "staged use executed as a function".into();
    COMPTIME_CALL_DEPTH: usize = "M0029" => |depth| format!("comptime call depth exceeded {depth}");
    COMPTIME_FUNCTION_UNAVAILABLE: String = "M0030" => |function| format!("function {function} is not available during comptime evaluation");
    COMPTIME_RUNTIME_FUNCTION: () = "M0031" => |_| "runtime functions cannot be executed at compile time".into();
    COMPTIME_FUNCTION_UNDEFINED: String = "M0032" => |function| format!("function {function} has no definition to interpret");
    COMPTIME_ARRAY_INDEX: String = "M0033" => |value| format!("array index is not an integer constant: {value}");
    COMPTIME_LOCAL_ADDRESS: () = "M0034" => |_| "cannot take the address of a local value in a comptime context".into();
    COMPTIME_GLOBAL_PROJECTION: () = "M0035" => |_| "cannot project into this global in a comptime context".into();
    COMPTIME_BITFIELD_ADDRESS: () = "M0036" => |_| "address-of a bitfield is not supported in a comptime context".into();
    COMPTIME_INVALID_FIELD_PROJECTION: () = "M0037" => |_| "invalid field projection in an address-of computation".into();
    COMPTIME_NON_ARRAY_INDEX: () = "M0038" => |_| "index projection on a non-array in an address-of computation".into();
    COMPTIME_NEGATIVE_INDEX: () = "M0039" => |_| "negative array index in an address-of computation".into();
    COMPTIME_INVALID_ELEMENT_LAYOUT: () = "M0040" => |_| "invalid element layout in an address-of computation".into();
    COMPTIME_VARIANT_ADDRESS: () = "M0041" => |_| "variant projections are not supported in address-of computations".into();
    COMPTIME_STRING_TYPE_UNAVAILABLE: () = "M0042" => |_| "the string type is unavailable during comptime evaluation".into();
    COMPTIME_UNKNOWN_GLOBAL_ADDRESS: () = "M0043" => |_| "unknown global in an address-of computation".into();
    COMPTIME_STAGED_CONCRETE: () = "M0044" => |_| "staged value used as a concrete value".into();
    COMPTIME_STAGED_PROJECTION: () = "M0045" => |_| "cannot project through a staged value".into();
    COMPTIME_STAGED_GLOBAL_STORE: () = "M0046" => |_| "cannot store a staged value in a global".into();
    COMPTIME_STAGED_ASSIGNMENT: () = "M0047" => |_| "cannot assign through a staged value".into();
    COMPTIME_STAGED_AGGREGATE_STORE: () = "M0048" => |_| "cannot store a staged value in an aggregate projection".into();
    COMPTIME_GLOBAL_CYCLE: () = "M0049" => |_| "cyclic dependency between global initializers".into();
    COMPTIME_STAGED_GLOBAL_RESULT: () = "M0050" => |_| "global initializer returned a staged value".into();
    COMPTIME_GLOBAL_UNAVAILABLE: () = "M0051" => |_| "global is not available during comptime evaluation".into();
    
    MIR_EXPECTED_CONSTANT: () = "M0052" => |_| "expected a compile-time value".into();
    MIR_FUNCTION_RETURN: String = "M0053" => |name| format!("Function '{name}' with non-void return type must have an explicit return statement");
    MIR_RUNTIME_LOCAL: () = "M0058" => |_| "expression depends on a runtime local".into();
    MIR_ARRAY_TOO_LONG: (usize, usize) = "M0059" => |(actual, length)| format!("array initializer has {actual} elements but the array length is {length}");
    MIR_MOVE_VALUE: String = "M0060" => |value| format!("Cannot move value: {value}");
    MIR_TEMPLATE_UNKNOWN_SCOPE: () = "M0061" => |_| "template place refers to an unknown scope".into();
    MIR_TEMPLATE_PARAMETER_DECLARATION: () = "M0062" => |_| "template block parameter has no declaration".into();
    MIR_STAGED_ENTRY_BLOCK: () = "M0063" => |_| "staged template has no entry block".into();
    MIR_MISSING_STAGED_BLOCK: () = "M0064" => |_| "missing staged block".into();
    MIR_STAGED_CALLEE_INPUT: () = "M0065" => |_| "staged callee is not a template input".into();
    MIR_STAGED_DEPENDENCY: () = "M0066" => |_| "staged callee has no dependency binding".into();
    MIR_COMPTIME_CALLEE_BINDING: () = "M0067" => |_| "comptime callee has no function binding".into();
    MIR_COMPTIME_FUNCTION_DEFINITION: () = "M0068" => |_| "comptime function has no MIR definition".into();
    MIR_STAGED_TARGET_BLOCK: () = "M0069" => |_| "staged target refers to an unknown block".into();
    MIR_TEMPLATE_PLACE_REWRITE: () = "M0070" => |_| "template place has no rewrite".into();
    MIR_TEMPLATE_BLOCK_REWRITE: () = "M0071" => |_| "template block target has no rewrite".into();
    MIR_YIELD_SCOPE: () = "M0072" => |_| "yield expression is not inside a yieldable scope".into();
    MIR_CONSTANT_VALUE: String = "M0073" => |context| format!("expression in {context} did not evaluate to a MIR constant");
    MIR_RUNTIME_CAPTURE_ESCAPE: () = "M0074" => |_| "a staged value with runtime captures escaped its originating function".into();
    MIR_STAGED_BINDING_COUNT: () = "M0075" => |_| "staged value binding count does not match its template".into();
    MIR_STAGED_CAPTURE_PLACE: () = "M0076" => |_| "staged place capture is not a place reference".into();
    MIR_STAGED_TARGET_NAME: String = "M0077" => |name| format!("staged {name} has no target in the materialization context");
    MIR_STAGED_YIELD_TARGET: () = "M0078" => |_| "staged yield has no target in the materialization context".into();
    MIR_COMPTIME_RUNTIME_ARGUMENT: () = "M0079" => |_| "comptime argument depends on a runtime value".into();
    MIR_PARAMETERIZED_STAGED_USE: () = "M0080" => |_| "parameterized staged value used without an application".into();
    MIR_STAGED_YIELD_VALUE: () = "M0081" => |_| "staged yield value does not match the materialization context".into();
    MIR_STAGED_YIELD_TYPE: () = "M0082" => |_| "staged yield type does not match the materialization context".into();
    MIR_TEMPLATE_REGISTER_REWRITE: String = "M0083" => |register| format!("template register {register} has no rewrite");
    MIR_RETAINED_PARAMETER: () = "M0084" => |_| "staged template retained a comptime function parameter".into();
    MIR_OUTPUT_REGISTER_REWRITE: () = "M0085" => |_| "instruction output register has no concrete rewrite".into();
    MIR_NESTED_STAGED: () = "M0086" => |_| "nested staged instruction was not expanded".into();
    MIR_INCOMPATIBLE_GLOBAL: String = "M0087" => |name| format!("Incompatible global declaration '{name}'");
    MIR_GLOBAL_INITIALIZER: String = "M0088" => |name| format!("Global '{name}' cannot have an initializer");
    MIR_DUPLICATE_GLOBAL: String = "M0089" => |name| format!("Duplicate global definition '{name}'");
    MIR_CONTROL_FLOW_TARGET: () = "M0090" => |_| "control-flow expression has no target scope".into();
    MIR_SWITCH_INTEGER: () = "M0091" => |_| "switch case expression must evaluate to an integer".into();
    MIR_BINDING_PATTERN: () = "M0092" => |_| "Binding patterns are only supported in match arms".into();
    MIR_INVALID_TYPE: String = "M0054" => |id| format!("invalid MIR type {id}");
    MIR_RECURSIVE_TYPE: String = "M0094" => |id| format!("cannot compute layout of recursive MIR type {id}");
    MIR_INVALID_BITFIELD_WIDTH: (usize, usize) = "M0095" => |(width, storage_bits)| format!("invalid bitfield width: {width} exceeds storage size of {storage_bits} bits");

    MIR_LOCAL_NOT_FOUND: String = "MX055" => |local| format!("could not find local id {local}");
    MIR_GLOBAL_NOT_FOUND: String = "MX056" => |name| format!("global variable '{name}' not found");
    MIR_FUNCTION_NOT_FOUND: String = "MX057" => |name| format!("function '{name}' not found");
    MIR_INVALID_ALIGNMENT: usize = "MX096" => |alignment| format!("invalid type alignment {alignment}");
    MIR_GLOBAL_MISSING: String = "MX099" => |id| format!("global {id} is not present in the MIR unit");
    MIR_INVALID_FIELD: (String, usize) = "MX097" => |(ty, field)| format!("MIR type {ty} has no field at index {field}");
    MIR_DUPLICATE_TYPE: String = "MX093" => |id| format!("MIR type {id} was defined more than once");
    MIR_GLOBAL_NOT_VARIABLE: String = "MX100" => |id| format!("attempted to materialize global {id} which is not a variable");
    MIR_GLOBAL_NOT_INITIALIZER: String = "MX101" => |id| format!("global {id} does not have a pending initializer");
    MIR_SIZE_OVERFLOW: () = "M0098" => |_| "MIR type layout size overflowed usize".into();
}
