use super::define_errors;

define_errors! {
    UNSUPPORTED_EXTERN_ABI: String = "P0001" => |abi| format!("Unsupported extern ABI '{abi}'");
    UNEXPECTED_END_INCLUDED: () = "P0002" => |()| "Unexpected end of included source".into();
    CANNOT_IMPORT_CURRENT_MODULE: (String,) = "P0003" => |(name,)| format!("Cannot import current module '{name}'");
    UNEXPECTED_SPECIFIER: () = "P0004" => |()| "Unexpected specifier in global scope".into();
    TYPEDEF_NAME: () = "P0005" => |()| "Typedef must have a name!".into();
    TEMPLATED_FUNCTION_BODY: () = "P0006" => |()| "Templated functions must be defined in place.".into();
    GLOBAL_END: () = "P0007" => |()| "Reached end of token stream when parsing global expression!".into();
    VARIABLE_AFTER_COMMA: () = "P0008" => |()| "Expected variable name after ','".into();
    GLOBAL_SEPARATOR: () = "P0009" => |()| "Expected ',' or ';' after global declaration".into();
    GLOBAL_TOKEN: (String,) = "P0010" => |(token,)| format!("Unexpected token in global expression: {token}");
    THEN_DIRECT_BODY: () = "P0011" => |()| "'then' must be the direct body of a staged expression".into();
    ONE_THEN: () = "P0012" => |()| "A statement may contain only one 'then' continuation".into();
    INTRINSIC_IDENTIFIER: () = "P0013" => |()| "Expected intrinsic identifier".into();
    IMPORT_END: () = "P0014" => |()| "Reached end of token stream when parsing import!".into();
    IMPORT_PATH_EMPTY: () = "P0015" => |()| "Import path cannot be empty".into();
    IMPORT_PATH_ITEM: () = "P0016" => |()| "Expected import path item".into();
    IMPORT_SEPARATOR: () = "P0017" => |()| "Expected ',' or '}' after import path item".into();
    IMPORT_TOP_LEVEL: () = "P0018" => |()| "Top-level import paths must be enclosed in '{' and '}'".into();
    IMPORT_BEFORE_COMMA: () = "P0019" => |()| "Expected import path item before ','".into();
    IMPORT_UNEXPECTED_CLOSE: () = "P0020" => |()| "Unexpected '}' in import statement".into();
    IMPORT_BEFORE_CLOSE: () = "P0021" => |()| "Expected import path item before '}'".into();
    IMPORT_TOKEN: (String,) = "P0022" => |(token,)| format!("Reached invalid token in import path: {token}");
    IMPORT_ALIAS: () = "P0023" => |()| "Expected identifier for import alias".into();
    ACCESS_FIELD: () = "P0024" => |()| "Expected field name in @unpack binding".into();
    ACCESS_BINDING: () = "P0025" => |()| "Expected binding name in @unpack binding".into();
    UNKNOWN_INTRINSIC: (String,) = "P0026" => |(ident,)| format!("Unknown intrinsic expression '{ident}'");
    CONDITIONAL_EXPRESSION: () = "P0027" => |()| "Expected expression before '?'".into();
    EXPRESSION_END: (String,) = "P0028" => |(kind,)| format!("Expected expression at end of {kind}");
    EXPRESSION_STACK: (String,) = "P0029" => |(kind,)| format!("Unexpected expression stack state while parsing {kind}");
    BINDING_TEMPLATE: () = "P0030" => |()| "Binding patterns may not have template input".into();
    PATTERN_VALUE: () = "P0031" => |()| "Expected pattern value".into();
    OPERATOR_STACK: () = "P0032" => |()| "Operator stack is empty when trying to compress expression".into();
    ACCESS_BRACE: () = "P0033" => |()| "Expected '{' after '.' in expression".into();
    STAGED_PARAMETER: () = "P0034" => |()| "Expected staged expression parameter name".into();
    UNRESOLVED_VARIABLE_TYPE: () = "P0035" => |()| "Could not resolve type for variable declaration".into();
    EXPRESSION_VALUE: () = "P0036" => |()| "Expected expression value".into();
    IDENTIFIER: () = "P0037" => |()| "Expected identifier".into();
    INITIALIZER_NAME: (String,) = "P0038" => |(ty,)| format!("Expected variable name for initializer of type {ty}");
    MATCH_DEFAULT: () = "P0039" => |()| "Match arms use binding patterns; replace 'default' with '_' to discard the binding".into();
    RESERVED_COMPTIME: () = "P0040" => |()| "'comptime' is reserved but is not implemented yet".into();
    RESERVED_EXPR: () = "P0041" => |()| "'expr' is reserved but is not implemented yet".into();
    UNEXPECTED_TOKEN: () = "P0042" => |()| "Unexpected token".into();
    ASSOCIATED_FUNCTION: bool = "P0043" => |comptime| {
        let kind = if comptime { "comptime function" } else { "function" };
        format!("Associated {kind} declarations must have exactly two segments")
    };
    COMPTIME_FUNCTION_NAME: () = "P0044" => |()| "Expected comptime function name".into();
    COMPTIME_FUNCTION_PARAMS: () = "P0045" => |()| "Expected comptime function parameter list".into();
    STAGED_PARAM_TYPE_NAME: () = "P0046" => |()| "Staged expression parameter types cannot have names".into();
    DUPLICATE_PRECONDITION: () = "P0047" => |()| "Precondition already defined in function contract.".into();
    DUPLICATE_POSTCONDITION: () = "P0048" => |()| "Postcondition already defined in function contract.".into();
    UNCLOSED_DECLARATION: () = "P0049" => |()| "Unclosed parenthesized declaration suffix".into();
    QUALIFIED_IDENTIFIER: () = "P0050" => |()| "Expected identifier after '::' in qualified name".into();
    INVALID_BINARY_OPERATOR: (String,) = "P0051" => |(op,)| format!("Invalid binary operator: {op}");
    BINARY_OPERATOR_COMMA: () = "P0052" => |()| "Invalid token: expected binary operator, found comma".into();
    AMBIGUOUS_LOOKUP: (String, String) = "P0053" => |(name, candidates)| format!("Ambiguous identifier '{name}', candidates: {candidates}");
    MULTIPLE_DEFAULT: () = "P0054" => |()| "Multiple default cases in switch statement".into();
    GOTO_LABEL: () = "P0055" => |()| "Expected label identifier after 'goto'".into();
    DECLARATION_NAME: () = "P0056" => |()| "Expected variable name in declaration".into();
    TEMPLATE_TYPE: () = "P0057" => |()| "Expected type declaration in template arguments!".into();
    ATTRIBUTE: (String, String) = "P0058" => |(kind, attribute)| format!("Unknown {kind} attribute '@{attribute}'");
    BITFIELD_WIDTH: () = "P0059" => |()| "Expected non-negative integer literal bitfield width".into();
    NAMELESS_MEMBER: (String,) = "P0060" => |(ty,)| format!("UNSUPPORTED: Nameless aggregate member of type {ty}");
    PREDECLARATION_NAME: () = "P0061" => |()| "Predeclaration must have a name".into();
    STRUCT_NAME: () = "P0062" => |()| "Struct name must be a simple identifier".into();
    ENUM_VARIANT: () = "P0063" => |()| "Expected enum variant name".into();
    QUALIFIED_TYPE_NAME: () = "P0064" => |()| "Expected name found qualified identifier".into();
    TAGGED_UNION_NAME: () = "P0065" => |()| "Tagged unions must have a name".into();
    TAGGED_VARIANT_NAME: () = "P0066" => |()| "Expected variant name in tagged union".into();
    TAGGED_VARIANT_NAMED: () = "P0067" => |()| "Tagged union variant may not have a named type".into();
    TAGGED_VARIANT_TYPE: () = "P0068" => |()| "Failed to parse tagged union variant type".into();
    UNION_NAME: () = "P0069" => |()| "Union name must be a simple identifier".into();
    TYPE_BASE_END: () = "P0070" => |()| "Expected type base, found end of tokens.".into();
    TYPE_BASE_TOKEN: String = "P0071" => |token| format!("Expected type base (identifier, struct, enum, union, or intrinsic), found: {token}");
    EXPECTED_TOKEN: (String, Option<String>) = "P0072" => |(expected, found)| {
        let found = found.unwrap_or_else(|| "end of input".to_owned());
        format!("Expected {expected}\n Found: {found}")
    };
    UNEXPECTED_END_TOKENS: () = "P0073" => |()| "Unexpected end of tokens".into();
    FAILED_EXPRESSION: (String,) = "P0074" => |(text,)| format!("Failed to parse expression value after operator: {text}");
    EXPRESSION_STACK_REMAINS: (String,) = "P0075" => |(text,)| format!("Expression stack is not empty after parsing expression: {text}");
    OPERATOR_STACK_REMAINS: (String,) = "P0076" => |(text,)| format!("Operator stack is not empty after parsing expression: {text}");
    READ_SOURCE: (String, String) = "P0077" => |(path, error)| format!("Failed to read source file {path}: {error}");
    READ_BUILTIN: (String, String) = "P0078" => |(path, error)| format!("Failed to read internal builtin header {path}: {error}");
    EXPECTED_DIRECTIVE: () = "P0079" => |()| "Expected preprocessor directive".into();
    EXPECTED_DIRECTIVE_HASH: () = "P0080" => |()| "Expected preprocessor directive after '#'".into();
    UNIMPLEMENTED_DIRECTIVE: String = "P0081" => |dir| format!("Preprocessor directive '{dir}' is not yet implemented");
    INCLUDE_PATH: () = "P0082" => |()| "#include requires a file path".into();
    INCLUDE_SYNTAX: String = "P0083" => |file| format!("Invalid include path '{file}': expected \"...\" or <...>");
    INCLUDE_NOT_FOUND: String = "P0084" => |file| format!("Included file not found: {file}");
    READ_INCLUDE: (String, String) = "P0085" => |(path, error)| format!("Failed to read included file {path}: {error}");
    CONDITIONAL_MACRO: String = "P0086" => |directive| format!("{directive} requires a macro name");
    ELIF_AFTER_ELSE: () = "P0087" => |()| "#elif after #else".into();
    ELIF_WITHOUT_IF: () = "P0088" => |()| "#elif without matching #if".into();
    ELSE_WITHOUT_IF: () = "P0089" => |()| "#else without matching #if".into();
    DUPLICATE_ELSE: () = "P0090" => |()| "Duplicate #else".into();
    ENDIF_WITHOUT_IF: () = "P0091" => |()| "#endif without matching #if".into();
    DEFINE_MACRO: () = "P0092" => |()| "#define requires a macro name".into();
    PREPROCESSOR_ERROR: String = "P0093" => |message| format!("#error{}{}", if message.trim().is_empty() { "" } else { ": " }, message.trim());
    INVALID_NUMBER: String = "P0094" => |number| format!("Invalid numeric literal: {number}");
    INVALID_CHAR: () = "P0095" => |()| "Invalid character literal".into();
    UNTERMINATED_CHAR: () = "P0096" => |()| "Unterminated character literal".into();
    EVAL_EXPRESSION: () = "P0097" => |()| "Failed to evaluate preprocessor expression".into();
    UNCLOSED_CONDITIONAL: String = "P0098" => |branch| format!("Unclosed preprocessor conditional starting in {branch} branch");
    NON_TEMPLATED_IDENTIFIER: () = "P0099" => |()| "Expected non-templated identifier".into();
}
