use super::define_errors;

define_errors! {
    ASSIGN_TO_CONST: () = "T0001" => |()| "Cannot assign to a const type".into();
    COMPTIME_FUNCTION_RUNTIME_CONTEXT: () = "T0015" => |()| "Comptime function cannot be used in runtime contexts".into();
    STAGED_EXPRESSION_RUNTIME_CONTEXT: () = "T0016" => |()| "Staged expression cannot be used in runtime contexts".into();
    TEMPLATE_DEDUCTION: () = "T0017" => |()| "Could not deduce arguments to template".into();
    SYMBOL_NOT_VALUE: () = "T0018" => |()| "Symbol does not refer to a value".into();
    POP_EMPTY_SCOPE: () = "T0019" => |()| "Attempted to pop a scope from an empty scope stack".into();
    GLOBAL_REDECLARATION: String = "T0020" => |arg0| format!("Attempting to redeclare global '{arg0}'.");
    COMPTIME_DEFINITION_WAS_NOT_FOUND: String = "T0021" => |arg0| format!("Comptime definition '{arg0}' was not found");
    SYMBOL_IS_NOT_A_COMPTIME_FUNCTION: String = "T0022" => |arg0| format!("Symbol '{arg0}' is not a comptime function");
    TYPE_IS_INCOMPLETE: String = "T0023" => |arg0| format!("Type '{arg0}' is incomplete");
    TYPE_IS_INCOMPLETE_24: String = "T0024" => |arg0| format!("{arg0} type is incomplete");
    TYPE_COMPONENT_CANNOT_BE_UNREACHABLE: String = "T0025" => |arg0| format!("{arg0} type component cannot be 'unreachable'");
    TYPE_IS_UNSIZED_AND_CANNOT_BE_DIRECTLY_ALLOCATED: String = "T0026" => |arg0| format!("{arg0} type is unsized and cannot be directly allocated");
    TYPE_NOT_FOUND: String = "T0027" => |arg0| format!("Type not found: {arg0}");
    TYPE_DOES_NOT_ACCEPT_TEMPLATE_ARGUMENTS: String = "T0028" => |arg0| format!("Type '{arg0}' does not accept template arguments");
    SYMBOL_IS_NOT_A_TYPE: String = "T0029" => |arg0| format!("Symbol '{arg0}' is not a type");
    TYPE_REQUIRES_TEMPLATE_ARGUMENTS: String = "T0030" => |arg0| format!("Type '{arg0}' requires template arguments");
    FAILED_TO_APPLY_TEMPLATE_ARGUMENTS: () = "T0031" => |()| "Failed to apply template arguments".into();
    TEMPLATE_ARGUMENTS_DID_NOT_RESOLVE_TYPE_TO_A_CONCRETE_TYPE: String = "T0032" => |arg0| format!("Template arguments did not resolve type '{arg0}' to a concrete type");
    AGGREGATE_FIELD_HAS_RECURSIVE_TYPE: String = "T0033" => |arg0| format!("Aggregate field '{arg0}' has recursive type");
    AGGREGATE_FIELD_HAS_INCOMPLETE_TYPE: String = "T0034" => |arg0| format!("Aggregate field '{arg0}' has incomplete type");
    AGGREGATE_FIELD_HAS_INVALID_TYPE: (String, String) = "T0035" => |(arg0, arg1)| format!("Aggregate field '{arg0}' has invalid type '{arg1}'");
    DROPPABLE_AGGREGATE_NODROP_FIELD: String = "T0036" => |arg0| format!("Aggregate containing nodrop field '{arg0}' must also be marked as @nodrop");
    COPYABLE_AGGREGATE_NOCOPY_FIELD: String = "T0037" => |arg0| format!("Aggregate containing nocopy field '{arg0}' must also be marked as @nodrop");
    SAFE_MOVE_AGGREGATE_UNSAFE_MOVE_FIELD: String = "T0038" => |arg0| format!("Aggregate containing unsafe_move field '{arg0}' must also be marked as @unsafe_move");
    COPY_TRAITS_TARGET_IS_NOT_A_VALID_TYPE: String = "T0039" => |arg0| format!("copy_traits target '{arg0}' is not a valid type");
    COPY_TRAITS_TARGET_IS_NOT_A_TYPE: String = "T0040" => |arg0| format!("copy_traits target '{arg0}' is not a type");
    BITFIELD_HAS_INCOMPLETE_TYPE: String = "T0041" => |arg0| format!("Bitfield '{arg0}' has incomplete type");
    TEMPLATED_FUNCTION_NOT_FOUND_42: String = "T0042" => |arg0| format!("Templated function '{arg0}' not found");
    SYMBOL_DOES_NOT_ACCEPT_TEMPLATE_ARGUMENTS_43: String = "T0043" => |arg0| format!("Symbol '{arg0}' does not accept template arguments");
    SYMBOL_IS_NOT_A_TEMPLATE: String = "T0044" => |arg0| format!("Symbol '{arg0}' is not a template");
    FUNCTION_TEMPLATE_EXPECTS_ARGUMENTS_FOUND: (String, String) = "T0045" => |(arg0, arg1)| format!("Function template expects {arg0} arguments, found {arg1}");
    COULD_NOT_DEDUCE_TEMPLATE_ARGUMENT_FOR_FUNCTION: (String, String) = "T0046" => |(arg0, arg1)| format!("Could not deduce template argument '{arg0}' for function {arg1}");
    EXPECTED_REALIZED_TEMPLATE_TYPE_WHILE_DEDUCING_FOUND: (String, String) = "T0047" => |(arg0, arg1)| format!("Expected realized template type '{arg0}' while deducing, found {arg1}");
    EXPECTED_TEMPLATE_TYPE_FOUND: (String, String) = "T0048" => |(arg0, arg1)| format!("Expected template type '{arg0}', found '{arg1}'");
    TEMPLATE_ARITY_MISMATCH_FOR_EXPECTED_FOUND: (String, String, String) = "T0049" => |(arg0, arg1, arg2)| format!("Template arity mismatch for '{arg0}': expected {arg1}, found {arg2}");
    TEMPLATE_DEDUCTION_FN_PTR_VARARGS_MISMATCH: (String, String) = "T0050" => |(arg0, arg1)| format!("Function pointer varargs mismatch during template deduction: expected {arg0}, found {arg1}");
    TEMPLATE_DEDUCTION_FN_PTR_ARITY_MISMATCH: (String, String) = "T0051" => |(arg0, arg1)| format!("Function pointer arity mismatch during template deduction: expected {arg0}, found {arg1}");
    CONFLICTING_DEDUCTIONS_FOR_TEMPLATE_ARGUMENT_VS: (String, String, String) = "T0052" => |(arg0, arg1, arg2)| format!("Conflicting deductions for template argument '{arg0}': {arg1} vs {arg2}");
    TEMPLATE_DEDUCTION_MISMATCH_EXPECTED_FOUND: (String, String) = "T0053" => |(arg0, arg1)| format!("Template deduction mismatch: expected {arg0}, found {arg1}");
    SYMBOL_HAS_INCOMPATIBLE_TAG_DECLARATIONS: String = "T0054" => |arg0| format!("Symbol '{arg0}' has incompatible tag declarations");
    AMBIGUOUS_SYMBOL_REFERENCE_CANDIDATES: String = "T0055" => |arg0| format!("Ambiguous Symbol Reference, candidates: {arg0}");
    SYMBOL_HAS_NO_DECLARATIONS: String = "T0056" => |arg0| format!("Symbol '{arg0}' has no declarations");
    SYMBOL_HAS_INCOMPATIBLE_DECLARATIONS: String = "T0057" => |arg0| format!("Symbol '{arg0}' has incompatible declarations");
    TYPE_HAS_NO_DECLARATIONS: String = "T0058" => |arg0| format!("Type '{arg0}' has no declarations");
    SYMBOL_HAS_MULTIPLE_TYPE_DEFINITIONS: String = "T0059" => |arg0| format!("Symbol '{arg0}' has multiple type definitions");
    TYPE_CONSTRUCTOR_TARGET_IS_NOT_A_TAGGED_UNION: () = "T0060" => |()| "Type constructor target is not a tagged union".into();
    TYPE_CONSTRUCTOR_VARIANT_INDEX_IS_OUT_OF_BOUNDS: String = "T0061" => |arg0| format!("Type constructor variant index {arg0} is out of bounds");
    TEMPLATE_EXPECTS_ARGUMENTS_FOUND: (String, String, String) = "T0062" => |(arg0, arg1, arg2)| format!("Template '{arg0}' expects {arg1} arguments, found {arg2}");
    CANNOT_COERCE_INITIALIZER_TO_TYPE: String = "T0063" => |arg0| format!("Cannot coerce initializer to type {arg0}");
    EXPECTED_A_UNION_TYPE_FOR_INITIALIZER_FOUND: String = "T0064" => |arg0| format!("Expected a union type for initializer, found {arg0}");
    UNION_INITIALIZER_MAY_CONTAIN_AT_MOST_ONE_ELEMENT: () = "T0065" => |()| "Union initializer may contain at most one element".into();
    UNION_INITIALIZER_FIELD_DOES_NOT_EXIST: () = "T0066" => |()| "Union initializer field does not exist".into();
    ARRAY_INITIALIZER_CANNOT_HAVE_NAMED_INDICES_FOUND: String = "T0067" => |arg0| format!("Array initializer cannot have named indices, found: {arg0}");
    EXPECTED_A_STRUCTURED_TYPE_FOR_INITIALIZER_FOUND: String = "T0068" => |arg0| format!("Expected a structured type for initializer, found {arg0}");
    STRUCTURED_INITIALIZER_HAS_UNEXPECTED_FIELD: String = "T0069" => |arg0| format!("Structured initializer has unexpected field: {arg0}");
    TOO_MANY_ELEMENTS_IN_STRUCT_INITIALIZER: () = "T0070" => |()| "Too many elements in struct initializer".into();
    FIELD_INITIALIZED_MORE_THAN_ONCE: String = "T0071" => |arg0| format!("Field '{arg0}' initialized more than once");
    COULD_NOT_FIND_FIELD_IN_TYPE: (String, String) = "T0072" => |(arg0, arg1)| format!("Could not find field '{arg0}' in type {arg1}");
    NO_EXPLICIT_CAST_FROM_TO: (String, String) = "T0073" => |(arg0, arg1)| format!("No explicit cast from {arg0} to {arg1}");
    NO_IMPLICIT_CAST_FROM_TO: (String, String) = "T0074" => |(arg0, arg1)| format!("No implicit cast from {arg0} to {arg1}");
    SAFE_PTR_DEREFERENCE: () = "T0075" => |()| "Dereferencing raw pointers is not allowed in safe contexts".into();
    UNREACHABLE_MATCH_ARM_AFTER_A_CATCH_ALL_BINDING: () = "T0076" => |()| "Unreachable match arm after a catch-all binding".into();
    MATCH_PATTERN_MUST_BE_AN_INTEGER_LITERAL_OR_A_CATCH: () = "T0077" => |()| "Match pattern must be an integer literal or a catch-all binding".into();
    INTEGER_VALUE_ALREADY_MATCHED_IN_THIS_MATCH: String = "T0078" => |arg0| format!("Integer value '{arg0}' already matched in this match");
    INTEGER_MATCH_MUST_BE_EXHAUSTIVE_ADD_A_CATCH_ALL_BINDING: () = "T0079" => |()| "Integer match must be exhaustive; add a catch-all binding such as '_ => ...'".into();
    UNREACHABLE_MATCH_ARM_ALL_TAGGED_UNION_VARIANTS_ARE_ALREADY_COVERED: () = "T0080" => |()| "Unreachable match arm: all tagged union variants are already covered".into();
    TAGGED_UNION_VARIANT_DOES_NOT_MATCH_THE_TYPE_BEING_MATCHED: (String, String) = "T0081" => |(arg0, arg1)| format!("Tagged union variant does not match the type being matched, found '{arg0}', expected '{arg1}'");
    VARIANT_NOT_FOUND_IN_TAGGED_UNION: (String, String) = "T0082" => |(arg0, arg1)| format!("Variant '{arg0}' not found in tagged union '{arg1}'");
    VARIANT_ALREADY_MATCHED_IN_THIS_MATCH_EXPRESSION: String = "T0083" => |arg0| format!("Variant '{arg0}' already matched in this match expression");
    VARIANT_OF_TAGGED_UNION_HAS_A_NON_VOID_TYPE_BUT: (String, String) = "T0084" => |(arg0, arg1)| format!("Variant '{arg0}' of tagged union '{arg1}' has a non-void type, but no inner name was provided in the pattern");
    MATCH_MUST_BE_EXHAUSTIVE_MISSING_VARIANTS_ADD_THE_MISSING_ARMS: String = "T0085" => |arg0| format!("Match must be exhaustive; missing variants: {arg0}. Add the missing arms or a catch-all binding such as '_ => ...'");
    MATCH_CONDITION_MUST_BE_AN_INTEGER_OR_TAGGED_UNION_TYPE: String = "T0086" => |arg0| format!("Match condition must be an integer or tagged union type, found {arg0}");
    VALUE_PRODUCING_MATCH_ARM_MAY_FALL_THROUGH_WITHOUT_YIELDING_A: () = "T0087" => |()| "Value-producing match arm may fall through without yielding a value".into();
    NON_TEMPLATED_TAGGED_UNION_PATTERN_MAY_NOT_HAVE_TEMPLATE_ARGUMENTS: () = "T0088" => |()| "Non-templated tagged union pattern may not have template arguments".into();
    TAGGED_UNION_PATTERN_TEMPLATE_ARGUMENTS_DO_NOT_MATCH_THE_MATCHED: () = "T0089" => |()| "Tagged union pattern template arguments do not match the matched type".into();
    RETURN_IS_NOT_ALLOWED_INSIDE_A_DEFERRED_EXPRESSION: () = "T0090" => |()| "return is not allowed inside a deferred expression".into();
    STAGED_RETURN_HAS_NO_MATERIALIZATION_CONTEXT: () = "T0091" => |()| "staged return has no materialization context".into();
    FUNCTION_CANNOT_RETURN_BECAUSE_ITS_RETURN_TYPE_IS_UNREACHABLE: String = "T0092" => |arg0| format!("Function {arg0} cannot return because its return type is 'unreachable'");
    CANNOT_RETURN_FROM_FUNCTION_WITH_A_VOID_RETURN_TYPE: String = "T0093" => |arg0| format!("Cannot return from function {arg0} with a void return type");
    FUNCTION_EXPECTS_A_RETURN_VALUE_BUT_NONE_WAS_PROVIDED: String = "T0094" => |arg0| format!("Function {arg0} expects a return value, but none was provided");
    CANNOT_HAVE_A_NAMED_RETURN_VARIABLE_IN_A_FUNCTION_WITH: () = "T0095" => |()| "Cannot have a named return variable in a function with void return type".into();
    SWITCH_CONDITION_MUST_BE_AN_INTEGER_TYPE_FOUND: String = "T0096" => |arg0| format!("Switch condition must be an integer type, found {arg0}");
    SWITCH_CASE_INDEX_OUT_OF_BOUNDS_BLOCK_HAS_EXPRESSIONS: (String, String) = "T0097" => |(arg0, arg1)| format!("Switch case index {arg0} out of bounds (block has {arg1} expressions)");
    SWITCH_DEFAULT_CASE_INDEX_OUT_OF_BOUNDS_BLOCK_HAS_EXPRESSIONS: (String, String) = "T0098" => |(arg0, arg1)| format!("Switch default case index {arg0} out of bounds (block has {arg1} expressions)");
    YIELD_IS_NOT_ALLOWED_INSIDE_A_DEFERRED_EXPRESSION: () = "T0099" => |()| "yield is not allowed inside a deferred expression".into();
    YIELD_USED_OUTSIDE_OF_A_YIELDING_CONTEXT: () = "T0100" => |()| "'yield' used outside of a yielding context".into();
    A_YIELD_CONTEXT_CANNOT_MIX_VALUE_AND_VALUELESS_YIELDS: () = "T0101" => |()| "A yield context cannot mix value and valueless yields".into();
    YIELD_TYPE_DOES_NOT_MATCH: (String, String) = "T0102" => |(arg0, arg1)| format!("Yield type {arg0} does not match {arg1}");
    YIELD_TARGET_EXPECTS_A_VALUE_OF_TYPE: String = "T0103" => |arg0| format!("Yield target expects a value of type {arg0}");
    SAFE_FUNCTION_MAY_NOT_USE_VARARGS: String = "T0104" => |arg0| format!("Safe function '{arg0}' may not use varargs");
    UNDEFINED_LABEL: String = "T0105" => |arg0| format!("Undefined label '{arg0}'");
    EXPECTED_A_STRUCT_OR_UNION_TYPE_ON_THE_LEFT_HAND: String = "T0106" => |arg0| format!("Expected a struct or union type on the left-hand side of an access expression, found {arg0}");
    INVALID_RIGHT_HAND_SIDE_OF_ACCESS_EXPRESSION_EXPECTED_AN_IDENTIFIER: () = "T0107" => |()| "Invalid right-hand side of access expression: expected an identifier".into();
    CANNOT_ASSIGN_TO_NON_REFERENCE_TYPE: String = "T0108" => |arg0| format!("Cannot assign to non-reference type {arg0}");
    EXPECTS_ARGUMENTS_FOUND: (String, String, String) = "T0109" => |(arg0, arg1, arg2)| format!("{arg0} expects {arg1} arguments, found {arg2}");
    EXPECTED_VA_LIST_FOUND: String = "T0110" => |arg0| format!("expected va_list, found {arg0}");
    ATTEMPTED_TO_CALL_VALUE_OF_NON_FUNCTION_TYPE: String = "T0111" => |arg0| format!("Attempted to call value of non-function type {arg0}");
    CALL_TO_EXPECTS_ARGUMENTS_FOUND: (String, String, String) = "T0112" => |(arg0, arg1, arg2)| format!("Call to {arg0} expects {arg1} arguments, found {arg2}");
    CALL_TO_EXPECTS_AT_LEAST_ARGUMENTS_FOUND: (String, String, String) = "T0113" => |(arg0, arg1, arg2)| format!("Call to {arg0} expects at least {arg1} arguments, found {arg2}");
    CANNOT_PASS_TO_VARARGS_EXPECTED_AN_INTRINSIC_TYPE_OR_POINTER: String = "T0114" => |arg0| format!("Cannot pass {arg0} to varargs: expected an intrinsic type or pointer");
    COULD_NOT_DEDUCE_CALLEE: () = "T0115" => |()| "Could not deduce callee".into();
    CALL_TO_COMPTIME_FUNCTION_EXPECTS_ARGUMENTS_FOUND: (String, String, String) = "T0116" => |(arg0, arg1, arg2)| format!("Call to comptime function {arg0} expects {arg1} arguments, found {arg2}");
    EXPECTED_A_PARAMETERIZED_STAGED_EXPRESSION: () = "T0117" => |()| "Expected a parameterized staged expression".into();
    STAGED_EXPRESSION_EXPECTS_ARGUMENTS_FOUND: (String, String) = "T0118" => |(arg0, arg1)| format!("Staged expression expects {arg0} arguments, found {arg1}");
    IS_OPERATOR_REQUIRES_A_TAGGED_UNION_ON_THE_LEFT_HAND: String = "T0119" => |arg0| format!("'is' operator requires a tagged union on the left-hand side, found {arg0}");
    IS_OPERATOR_LEFT_HAND_SIDE_TAGGED_UNION_TYPE_DOES_NOT: (String, String) = "T0120" => |(arg0, arg1)| format!("'is' operator left-hand side tagged union type {arg0} does not match right-hand side tagged union type {arg1}");
    IS_OPERATOR_VARIANT_NAME_NOT_FOUND_IN_TAGGED_UNION: (String, String) = "T0121" => |(arg0, arg1)| format!("'is' operator variant name '{arg0}' not found in tagged union {arg1}");
    TAGGED_UNION_PATTERN_TEMPLATE_ARGUMENTS_DO_NOT_MATCH_THE_LEFT: () = "T0122" => |()| "Tagged union pattern template arguments do not match the left-hand side type".into();
    INVALID_OPERANDS_TO_LOGICAL_OPERATION_AND: (String, String, String) = "T0123" => |(arg0, arg1, arg2)| format!("Invalid operands to logical operation {arg0}, {arg1} and {arg2}");
    INVALID_BINARY_OPERATION_FOR_TYPES_AND: (String, String, String) = "T0124" => |(arg0, arg1, arg2)| format!("Invalid binary operation {arg0} for types {arg1} and {arg2}");
    INVALID_FLOAT_BINARY_OPERATION_FOR_TYPES_AND: (String, String, String) = "T0125" => |(arg0, arg1, arg2)| format!("Invalid float binary operation {arg0} for types {arg1} and {arg2}");
    INVALID_BINARY_OPERATION_FOR_POINTER_TYPES: String = "T0126" => |arg0| format!("Invalid binary operation {arg0} for pointer types");
    INVALID_BINARY_OPERATION_FOR_POINTER_AND_NON_POINTER_TYPES: String = "T0127" => |arg0| format!("Invalid binary operation {arg0} for pointer and non-pointer types");
    INVALID_INTEGER_BINARY_OPERATION_FOR_TYPES_AND: (String, String, String) = "T0128" => |(arg0, arg1, arg2)| format!("Invalid integer binary operation {arg0} for types {arg1} and {arg2}");
    CANNOT_APPLY_PRE_INCREMENT_TO_NON_REFERENCE_TYPE: String = "T0129" => |arg0| format!("Cannot apply pre-increment to non-reference type {arg0}");
    PRE_INCREMENT_OPERATOR_REQUIRES_AN_INTEGER_OR_POINTER_TYPE_FOUND: String = "T0130" => |arg0| format!("Pre-increment operator requires an integer or pointer type, found {arg0}");
    BITWISE_NOT_OPERATOR_REQUIRES_AN_INTEGER_TYPE_FOUND: String = "T0131" => |arg0| format!("Bitwise NOT operator requires an integer type, found {arg0}");
    NEGATION_OPERATOR_REQUIRES_AN_INTEGER_OR_FLOAT_TYPE_FOUND: String = "T0132" => |arg0| format!("Negation operator requires an integer or float type, found {arg0}");
    CANNOT_TAKE_THE_ADDRESS_OF_A_NON_REFERENCE_TYPE: () = "T0133" => |()| "Cannot take the address of a non-reference type".into();
    CANNOT_DEREFERENCE_NON_POINTER_TYPE: String = "T0134" => |arg0| format!("Cannot dereference non-pointer type {arg0}");
    THE_LEFT_SIDE_OF_MUST_BE_A_FUNCTION_CALL: () = "T0135" => |()| "The left side of '<|' must be a function call".into();
    THE_RIGHT_SIDE_OF_MUST_BE_A_METHOD_CALL: () = "T0136" => |()| "The right side of '|>' must be a method call".into();
    EXPECTED_QUALIFIED_TAGGED_UNION_VARIANT_PATTERN: () = "T0137" => |()| "Expected qualified tagged union variant pattern".into();
    EXPECTED_TAGGED_UNION_VARIANT_PATTERN_TO_NAME_A_TYPE_MEMBER: () = "T0138" => |()| "Expected tagged union variant pattern to name a type member constructor".into();
    TAGGED_UNION_VARIANT_PAYLOAD_PATTERN_MUST_BE_A_BINDING: () = "T0139" => |()| "Tagged union variant payload pattern must be a binding".into();
    COULD_NOT_RESOLVE_PATTERN_TARGET: String = "T0140" => |arg0| format!("Could not resolve pattern target '{arg0}'");
    STAGED_EXPRESSION_CANNOT_BE_USED_AS_A_RUNTIME_EXPRESSION: () = "T0141" => |()| "Staged expression cannot be used as a runtime expression".into();
    COMPTIME_FUNCTION_CANNOT_BE_USED_AS_A_VALUE: () = "T0142" => |()| "Comptime function cannot be used as a value".into();
    COULD_NOT_DEDUCE_TEMPLATED_FUNCTION_PARAMETERS: () = "T0143" => |()| "Could not deduce templated function parameters".into();
    COULD_NOT_RESOLVE_EXPRESSION_EXPECTED_TYPE_REQUIRED_BUT_NOT_PROVIDED: () = "T0144" => |()| "Could not resolve expression, expected type required but not provided".into();
    COULD_NOT_RESOLVE_STAGED_EXPRESSION_STAGED_PARAMETER_TYPES_REQUIRED_BUT: () = "T0145" => |()| "Could not resolve staged expression, staged parameter types required but not provided".into();
    EXPRESSION_IS_NOT_SUPPORTED_IN_SAFE_CONTEXTS_WRAP_IT_IN: () = "T0146" => |()| "Expression is not supported in safe contexts; wrap it in `@unsafe`".into();
    STAGED_EXPRESSION_EXPECTS_PARAMETERS_FOUND: (String, String) = "T0147" => |(arg0, arg1)| format!("Staged expression expects {arg0} parameters, found {arg1}");
    A_YIELDING_BLOCK_MUST_YIELD_A_VALUE_ON_EVERY_PATH: () = "T0148" => |()| "A yielding block must yield a value on every path".into();
    NESTED_DEFER_IS_NOT_SUPPORTED: () = "T0149" => |()| "nested defer is not supported".into();
    DEFER_CANNOT_EXECUTE_WHILE_EVALUATING_A_COMPTIME_FUNCTION: () = "T0150" => |()| "defer cannot execute while evaluating a comptime function".into();
    DEFERRED_EXPRESSION_MUST_HAVE_TYPE_VOID_FOUND: String = "T0151" => |arg0| format!("deferred expression must have type void, found {arg0}");
    DEFERRED_EXPRESSION_MUST_FALL_THROUGH_NORMALLY: () = "T0152" => |()| "deferred expression must fall through normally".into();
    THEN_MAY_ONLY_CAPTURE_THE_REMAINDER_OF_AN_ENCLOSING_BLOCK: () = "T0153" => |()| "'then' may only capture the remainder of an enclosing block".into();
    BREAK_IS_NOT_ALLOWED_INSIDE_A_DEFERRED_EXPRESSION: () = "T0154" => |()| "break is not allowed inside a deferred expression".into();
    BREAK_USED_OUTSIDE_OF_A_LOOP_OR_SWITCH_CONTEXT: () = "T0155" => |()| "'break' used outside of a loop or switch context".into();
    CONTINUE_IS_NOT_ALLOWED_INSIDE_A_DEFERRED_EXPRESSION: () = "T0156" => |()| "continue is not allowed inside a deferred expression".into();
    CONTINUE_USED_OUTSIDE_OF_A_LOOP_CONTEXT: () = "T0157" => |()| "'continue' used outside of a loop context".into();
    GOTO_IS_NOT_ALLOWED_INSIDE_A_DEFERRED_EXPRESSION: () = "T0158" => |()| "goto is not allowed inside a deferred expression".into();
    DUPLICATE_LABEL: String = "T0159" => |arg0| format!("Duplicate label '{arg0}'");
    IDENTIFIER_NOT_FOUND: String = "T0160" => |arg0| format!("Identifier '{arg0}' not found");
    REFERENCES_TO_UNSAFE_FUNCTION_MAY_NOT_BE_USED_IN_SAFE: String = "T0161" => |arg0| format!("References to unsafe function `{arg0}` may not be used in safe contexts");
    INTEGER_LITERAL_DOES_NOT_FIT_ANY_PERMITTED_TYPE: String = "T0162" => |arg0| format!("Integer literal {arg0} does not fit any permitted type");
    LONG_DOUBLE_LITERALS_ARE_NOT_SUPPORTED_BY_THE_CURRENT_MIR: () = "T0163" => |()| "Long double literals are not supported by the current MIR".into();
    ATTEMPTING_TO_REDECLARE_VARIABLE_WITH_A_DIFFERENT_TYPE: String = "T0164" => |arg0| format!("Attempting to redeclare variable '{arg0}' with a different type.");
    MOVE_EXPRESSIONS_CAN_CURRENTLY_ONLY_BE_APPLIED_TO_STACK_VARIABLE: () = "T0165" => |()| "Move expressions can currently only be applied to stack variable identifiers".into();
    MOVING_OUT_OF_AGGREGATE_FIELDS_OR_PROJECTIONS_IS_NOT_IMPLEMENTED: () = "T0166" => |()| "Moving out of aggregate fields or projections is not implemented".into();
    MOVING_A_VALUE_OF_AN_UNSAFE_MOVE_TYPE_MUST_BE: () = "T0167" => |()| "Moving a value of an @unsafe_move type must be wrapped in @unsafe in safe functions".into();
    ADOPT_IS_UNSAFE_AND_MUST_BE_WRAPPED_IN_UNSAFE_IN: () = "T0168" => |()| "@adopt is unsafe and must be wrapped in @unsafe in safe functions".into();
    ADOPT_REQUIRES_AN_ADDRESSABLE_MEMORY_PLACE: () = "T0169" => |()| "@adopt must be applied to a reference type".into();
    ADOPT_CANNOT_ADOPT_FROM_A_CONST_MEMORY_PLACE: () = "T0170" => |()| "@adopt cannot adopt from a const memory place".into();
    ADOPT_OF_A_LOCAL_BINDING_IS_NOT_ALLOWED_USE_MOVE: () = "T0171" => |()| "@adopt of a local binding is not allowed; use move for local bindings".into();
    LEAK_IS_UNSAFE_AND_MUST_BE_WRAPPED_IN_UNSAFE_IN: () = "T0172" => |()| "@leak is unsafe and must be wrapped in @unsafe in safe functions".into();
    LEAK_CURRENTLY_REQUIRES_A_LOCAL_IDENTIFIER: () = "T0173" => |()| "@leak currently requires a local identifier".into();
    LEAK_ON_AGGREGATE_FIELDS_OR_PROJECTIONS_IS_NOT_IMPLEMENTED: () = "T0174" => |()| "@leak on aggregate fields or projections is not implemented".into();
    LEAK_REQUIRES_A_STACK_LOCAL_VALUE: () = "T0175" => |()| "@leak requires a stack local value".into();
    UNPACK_EXPECTS_AN_OWNED_STRUCT_TYPE: () = "T0176" => |()| "@unpack expects an owned struct type".into();
    UNPACK_FIELD_DOES_NOT_EXIST_ON: (String, String) = "T0177" => |(arg0, arg1)| format!("@unpack field '{arg0}' does not exist on {arg1}");
    UNPACK_FIELD_IS_BOUND_MORE_THAN_ONCE: String = "T0178" => |arg0| format!("@unpack field '{arg0}' is bound more than once");
    UNPACK_BINDING_IS_INTRODUCED_MORE_THAN_ONCE: String = "T0179" => |arg0| format!("@unpack binding '{arg0}' is introduced more than once");
    UNPACK_OF_MUST_BIND_NODROP_FIELD: (String, String) = "T0180" => |(arg0, arg1)| format!("@unpack of {arg0} must bind @nodrop field '{arg1}'");
}
