[package]
name = "cx-backend-cranelift"
version = "0.0.0"
edition = "2021"
autotests = false

[dependencies]
cx-log = { path = "../cx-log" }
cx-util = { path = "../cx-util" }
cx-lmir = { path = "../cx-lmir" }
cx-ast = { path = "../cx-ast" }

cranelift = "0.132.1"
cranelift-module = "0.132.1"
cranelift-native = "0.132.1"
cranelift-object = "0.132.1"
