[project]
name = "doomgeneric"

[build]
backend = "cranelift"
optimization = "O2"

[workspace.targets.default]
binaries = [
  { name = "doomgeneric", compile_all = ["upstream/doomgeneric/*.c", "doomgeneric_raylib.c"] },
]
native_objects = [
  "../artifacts/raylib/lib/raylib.o",
]
include_dirs = [
  "../../lib/libc",
  "../artifacts/raylib/include",
  "upstream/doomgeneric",
]
link = [
  { name = "m", kind = "system" },
  { name = "pthread", kind = "system" },
  { name = "dl", kind = "system" },
  { name = "rt", kind = "system" },
  { name = "X11", kind = "system" },
]
