[project]
name = "self-hosted"

[build]
backend = "cranelift"
optimization = "O0"

[workspace.targets.default]
binaries = [
  { name = "self-hosted", entry = "main.cx" },
]
libraries = [
  { name = "test-lib", entry = "test-lib.cxl" },
]