[package]
name = "cx-compiler-typechecker"
version = "0.1.0"
edition = "2021"

[dependencies]
cx-data-ast = { path = "../cx-data-ast" }
cx-data-bytecode = { path = "../cx-data-bytecode" }

cx-compiler-ast = { path = "../cx-compiler-ast" }
cx-compiler-modules = { path = "../cx-compiler-modules" }

cx-util = { path = "../cx-util" }