[package]
name = "cx-compiler-typechecker"
version = "0.1.0"
edition = "2021"

[dependencies]
cx-data-ast = { path = "../cx-data-ast" }
cx-compiler-ast = { path = "../cx-compiler-ast" }
cx-util = { path = "../cx-util" }