[package]
name = "cx-data-ast"
version = "0.0.0"
edition = "2021"

[dependencies]
cx-util = { path = "../cx-util" }
uuid = { version = "1.16.0", features = ["v4"] }

serde = { version = "1.0", features = ["derive"] }